require:
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'Gemfile.lock'
  Include:
    - '**/*.rb'
    - 'spec/**/*.rb'

Naming/FileName:
  Exclude:
    - 'Gemfile'

Layout/IndentationWidth:
  Enabled: true
  Width: 2

Style/Encoding:
  Enabled: true 

Lint/AmbiguousOperator:
  Enabled: true

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Style/HashEachMethods:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

RSpec/AnyInstance:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 20

RSpec/ExpectInHook:
  Enabled: false

RSpec/NestedGroups:
  Max: 7

RSpec/ContextWording:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/**/*'

RSpec/MultipleMemoizedHelpers:
  Max: 7

Lint/MissingSuper:
  Enabled: false